server:
  port: 8080

debug: false

logging:
  level:
    root: info
    org.mybatis: debug
    org.springframework: info
    org.springframework.jdbc: debug
    com.github.trang: debug
    com.github.archetype: debug

spring:
  datasource:
    url: jdbc:h2:file:./samples
    username: root
    password: 123456
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql